name: kana
version: 1.0.0
homepage: https://github.com/paulorobertocruz/kana
description: package to convert from kana(hiragana and katakana) to romaji and back
authors:
- Paulo Roberto Cruz <paulo.cruz9@gmail.com>
environment:
  sdk: '>=2.0.0 <3.0.0'

dev_dependencies:
  test: ^1.9.4